### ISSUE TITLE
proposal: improve diff messages 

### ISSUE THREAD

**Issue by trilopin** [gramos74/pt_mock#2]
Use a diff library like sebastian/diff and sebastian/comparator for improving error messages to user.

This libraries are used by phpunit (and developed by his creator) with great results.

Could be useful for with method.

**Comment by gramos74** [comment]
Once we can install this package via composer and its dependencies, I totally agree in to use both packages.

**Comment by trilopin** [comment]
This packages are installed in require-dev environment because are phpunit dependencies. 

I will test this in separate pull request.

**Comment by trilopin** [comment]
I have tested in my repo https://github.com/trilopin/pt_mock/commit/021760cc8f13fa06678e3568fdb02c88fe907cf1

old output

```
Pt\MockException: [Test]

Expected parameters for [method]:
Array
(
    [0] => 1
    [1] => Array
        (
            [index] => value
            [index2] => Array
                (
                    [0] => 2
                    [1] => 3
                    [2] => 6
                )

            [index3] => 1
        )

    [2] => 5
)

 But received :Array
(
    [0] => 1
    [1] => Array
        (
            [index] => value_other
            [index2] => Array
                (
                    [0] => 2
                    [1] => str
                )

            [index3] => 1
        )

    [2] => 5
)
```

new output 

```
Parameters mismatch for [method]: 
--- Expected
+++ Actual
@@ @@
 Array (
     0 => true
     1 => Array (
-        'index' => 'value'
+        'index' => 'value_other'
         'index2' => Array (
             0 => 2
-            1 => 3
-            2 => 6
+            1 => 'str'
         )
         'index3' => true
     )
     2 => 5
 )
```

it looks nice to me, what do you think?
would be great if output were coloured
